spring:
  datasource:
    #    url: jdbc:h2:tcp://localhost/~/memodb
    url: jdbc:h2:mem:memodb;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

logging:
  level:
    org:
      springframework:
        web: debug
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
decorator:
  datasource:
    p6spy:
      enable-logging: false